### ISSUE TITLE
同じ情報を何回も登録できちゃうでしょうか。なにか制御を入れたほうがいいかもです。

### ISSUE THREAD

**Issue by guangchuan** [taisetsunakimi/taisetsunakimi#19]
同じ情報を何回も登録できちゃうでしょうか。なにか制御を入れたほうがいいかもです。

**Comment by guangchuan** [comment]
メールアドレスと、誕生日をキーにして、同じであれば、上書きします。
DB上は１つのレコードになります。

**Comment by n-niibe** [comment]
黄さんのコメントの通り
Upsertするようになっています

問題ないようでしたら、クローズさせていただきます

**Comment by ozamasa** [comment]
了解です！ではクローズします！
